// <auto-generated />
using System;
using AIContentRemover.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIContentRemover.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("AIContentRemover.Models.TweetTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AiVotes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("NotAiVotes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("TweetId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("TweetId")
                        .IsUnique()
                        .HasDatabaseName("IX_TweetTags_TweetId");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_TweetTags_UpdatedAt");

                    b.HasIndex("AiVotes", "NotAiVotes")
                        .HasDatabaseName("IX_TweetTags_Votes");

                    b.ToTable("TweetTags", (string)null);
                });

            modelBuilder.Entity("AIContentRemover.Models.Vote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAiVote")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TweetTagId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserIdentifier")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VotedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress")
                        .HasDatabaseName("IX_Votes_IpAddress");

                    b.HasIndex("TweetTagId", "UserIdentifier")
                        .IsUnique()
                        .HasDatabaseName("IX_Votes_TweetTag_User");

                    b.ToTable("Votes", (string)null);
                });

            modelBuilder.Entity("AIContentRemover.Models.Vote", b =>
                {
                    b.HasOne("AIContentRemover.Models.TweetTag", "TweetTag")
                        .WithMany("Votes")
                        .HasForeignKey("TweetTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TweetTag");
                });

            modelBuilder.Entity("AIContentRemover.Models.TweetTag", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
